/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AskifyRouteImport } from './routes/askify'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as ChatsConversationIdRouteImport } from './routes/chats.$conversationId'
import { Route as ApiDeleteAccountRouteImport } from './routes/api/delete-account'
import { Route as ApiAskifyRouteImport } from './routes/api/askify'
import { Route as ApiPushSendRouteImport } from './routes/api/push.send'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AskifyRoute = AskifyRouteImport.update({
  id: '/askify',
  path: '/askify',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsConversationIdRoute = ChatsConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatsRoute,
} as any)
const ApiDeleteAccountRoute = ApiDeleteAccountRouteImport.update({
  id: '/api/delete-account',
  path: '/api/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskifyRoute = ApiAskifyRouteImport.update({
  id: '/api/askify',
  path: '/api/askify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSendRoute = ApiPushSendRouteImport.update({
  id: '/api/push/send',
  path: '/api/push/send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/askify': typeof AskifyRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/download': typeof DownloadRoute
  '/install': typeof InstallRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/askify': typeof ApiAskifyRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/api/push/send': typeof ApiPushSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/askify': typeof AskifyRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/download': typeof DownloadRoute
  '/install': typeof InstallRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/askify': typeof ApiAskifyRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/api/push/send': typeof ApiPushSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/askify': typeof AskifyRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/download': typeof DownloadRoute
  '/install': typeof InstallRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/api/askify': typeof ApiAskifyRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/api/push/send': typeof ApiPushSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/askify'
    | '/auth'
    | '/chats'
    | '/download'
    | '/install'
    | '/profile'
    | '/settings'
    | '/api/askify'
    | '/api/delete-account'
    | '/chats/$conversationId'
    | '/groups/$groupId'
    | '/api/push/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/askify'
    | '/auth'
    | '/chats'
    | '/download'
    | '/install'
    | '/profile'
    | '/settings'
    | '/api/askify'
    | '/api/delete-account'
    | '/chats/$conversationId'
    | '/groups/$groupId'
    | '/api/push/send'
  id:
    | '__root__'
    | '/'
    | '/askify'
    | '/auth'
    | '/chats'
    | '/download'
    | '/install'
    | '/profile'
    | '/settings'
    | '/api/askify'
    | '/api/delete-account'
    | '/chats/$conversationId'
    | '/groups/$groupId'
    | '/api/push/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskifyRoute: typeof AskifyRoute
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  InstallRoute: typeof InstallRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ApiAskifyRoute: typeof ApiAskifyRoute
  ApiDeleteAccountRoute: typeof ApiDeleteAccountRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  ApiPushSendRoute: typeof ApiPushSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/askify': {
      id: '/askify'
      path: '/askify'
      fullPath: '/askify'
      preLoaderRoute: typeof AskifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$conversationId': {
      id: '/chats/$conversationId'
      path: '/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ChatsConversationIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/api/delete-account': {
      id: '/api/delete-account'
      path: '/api/delete-account'
      fullPath: '/api/delete-account'
      preLoaderRoute: typeof ApiDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/askify': {
      id: '/api/askify'
      path: '/api/askify'
      fullPath: '/api/askify'
      preLoaderRoute: typeof ApiAskifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/send': {
      id: '/api/push/send'
      path: '/api/push/send'
      fullPath: '/api/push/send'
      preLoaderRoute: typeof ApiPushSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatsRouteChildren {
  ChatsConversationIdRoute: typeof ChatsConversationIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsConversationIdRoute: ChatsConversationIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskifyRoute: AskifyRoute,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  InstallRoute: InstallRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ApiAskifyRoute: ApiAskifyRoute,
  ApiDeleteAccountRoute: ApiDeleteAccountRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  ApiPushSendRoute: ApiPushSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
